### ISSUE TITLE
Exception when screen is locked on Android

### ISSUE THREAD

**Issue by havart-netcompany** [xamarin/xamarin.exposurenotification#55] opened 2020-05-28 13:27 UTC
When running your sample app on Android (with updated Google Play Services, checked in, whitelisted primary Google account) and uncomment the "ExposureNotification.OverrideNativeImplementation" statement from App.xaml.cs, it seems to be working fine while the screen is on. I am able to click "Turn on" and have the dialog pop up.

But when I lock the screen, 10 seconds will pass and then the application enters break mode and this exception is printed:

```
05-28 15:22:52.706 E/AndroidRuntime(21647): FATAL EXCEPTION: GoogleApiHandler
05-28 15:22:52.706 E/AndroidRuntime(21647): Process: com.xamarin.exposurenotification.sampleapp, PID: 21647
05-28 15:22:52.706 E/AndroidRuntime(21647): java.lang.IllegalStateException: Nonexistent connection status for service config: com.google.android.gms.nearby.exposurenotification.START
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at com.google.android.gms.common.internal.zze.zzb(com.google.android.gms:play-services-basement@@17.1.0:34)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at com.google.android.gms.common.internal.GmsClientSupervisor.zza(com.google.android.gms:play-services-basement@@17.1.0:11)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at com.google.android.gms.common.internal.BaseGmsClient.zza(com.google.android.gms:play-services-basement@@17.1.0:124)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at com.google.android.gms.common.internal.BaseGmsClient.disconnect(com.google.android.gms:play-services-basement@@17.1.0:166)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.1.0:210)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabn(com.google.android.gms:play-services-base@@17.1.0:203)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.1.0:186)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at android.os.Handler.dispatchMessage(Handler.java:103)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)Thread started:  #7

05-28 15:22:52.706 E/AndroidRuntime(21647): 	at android.os.Looper.loop(Looper.java:214)
05-28 15:22:52.706 E/AndroidRuntime(21647): 	at android.os.HandlerThread.run(HandlerThread.java:67)
**Java.Lang.IllegalStateException:** 'Nonexistent connection status for service config: com.google.android.gms.nearby.exposurenotification.START'
```

I have replicated the error on another app.

This error message is very similar to the one we solved previously, where the problem was that the generated AndroidManifest.xml for my app contained illegal permissions like BLUETOOTH_ADMIN

**Comment by havart-netcompany** [comment] 2020-05-28 13:30
I replicated the error on another device

**Comment by havart-netcompany** [comment] 2020-05-28 18:38
In the other project (Xamarin.Android), I notice that the exception was not thrown after I removed "isEnabled()" from the constructor of the Application class. Then I scheduled a PeriodicWorkRequest that runs isEnabledAsync(). This causes the same error to happen when I lock the screen. If I remove the call to isEnabledAsync() from the PeriodicWorkRequest's DoWork, then the error is not thrown anymore. It seems like Google Play Services refuses when we call EN API functions while the screen is locked. The weird thing is that even though the call to isEnabled() is preceded by a print statement, the print statement does not happen when the Exception is thrown. The Exception is thrown even if I keep the screen awake after locking.

**Comment by havart-netcompany** [comment] 2020-05-28 21:27
It also happens if the screen is unlocked, but I've left the phone idle for a few minutes

**Comment by Redth** [comment] 2020-05-29 00:59
@havart-netcompany so if you don't check for IsEnabled in the periodic work request, it is fine? That does seem odd....

**Comment by havart-netcompany** [comment] 2020-05-29 08:30
I've found a simpler way to explain the problem:
**If you have run any EN API function (let's say isEnabledAsync()) after starting the app, then you will get "FATAL EXCEPTION" 10 seconds after locking the screen.**

Here is a simple way to replicate it:
1. Use Visual Studio to create a new Android App (Xamarin) with the Single View App template
2. Migrate to Androidx, set Target Framework to 10, min SDK to 23 and target SDK to 29
3. Depend on the Xamarin.ExposureNotification 0.4.0-preview Nuget
4. Let MainActivity.FabOnClick only consist of this line:
`Xamarin.ExposureNotifications.ExposureNotification.IsEnabledAsync();`
5. Run the app
6. Click on the FAB
7. Lock the screen
8. Wait 10 seconds
9. FATAL EXCEPTION
10. Restart the app
11. Lock the screen
12. Wait 10 seconds
13. No FATAL EXCEPTION because you didn't click on the FAB

**Comment by havart-netcompany** [comment] 2020-05-29 08:38
By the way, "Lock the screen" is not the only way to replicate it. There are ways to get the FATAL EXCEPTION:
- Lock the screen
- Go to another app
- Wait 2 minutes for the app to become idle

**Comment by dlandi** [comment] 2020-05-29 08:39
<<Wait 2 minutes for the app to become idle
This may be the major clue...

**Comment by havart-netcompany** [comment] 2020-05-29 11:26
If I add a Foreground Notification, it takes 3 minutes before the FATAL EXCEPTION is thrown. Do you have any suggestions? It is crucial that we get this bug fixed

**Comment by dlandi** [comment] 2020-05-29 11:38
At a guess, it seems to me that a null value is being passed to a google service. The null may represent an object that has gone out of scope and been cleaned in-memory, while some passive service is still in memory. 

I would suggest that you search for this string below, and think about the Intent it is pointing to:

[BroadcastReceiver(Permission = "com.google.android.gms.nearby.exposurenotification.EXPOSURE_CALLBACK")]

**Comment by havart-netcompany** [comment] 2020-05-30 08:30
@dlandi I interpret this as an integral problem in the current Xamarin.ExposureNotification library, correct? Some state of the code causes an important object to be garbage collected. Is the ETA of the fix still an unknown? I hope we could possibly find a workaround from the outside, in the meantime, but I am not sure what approach to take for that

**Comment by dlandi** [comment] 2020-05-30 09:22
@havart-netcompany Total speculation, but that undocumented PreserveAttribute "[Preserve]" may not be functioning as expected. What happens if you comment out that attribute?

**Comment by havart-netcompany** [comment] 2020-05-30 11:29
**Breaking news!** I ran the Xamarin.ExposureNotification sample app with "nice bundle name" as the latest commit (the only change was to comment out the OverrideNativeImplementation statement). I click "turn on" on the app, the dialog pops up, I consent and turn off the screen. The error replicates in 10 seconds. Then I pull the newest changes, go through the same process and **the error does not happen**. Then I go into ExposureNotification and comment out [Xamarin.Forms.Internals.Presereve] line. The error still does not happen. So the question is what was changed to make it not happen between "nice bundle name" and "fix sample app settings" commits

**Comment by dlandi** [comment] 2020-05-30 12:02
> So the question is what was changed to make it not happen between "nice bundle name" and "fix sample app settings" commits

Well, do a diff comparison and see if you can spot the crucial change

**Comment by Redth** [comment] 2020-05-30 12:08
Was this after the bundle name change? I wonder if having upper case characters or something similar was causing issues. The default project template package name is not all lowercase.

**Comment by havart-netcompany** [comment] 2020-05-30 12:20
If I download your the latest version of the Xamarin.ExposureNotification project from the github and import it as a project, then the FATAL EXCEPTION doesn't happen. That's the same project where depending on the current Xamarin.ExposureNotification Nuget gives FATAL EXCEPTION. We'll see which change in the diff fixed it

**Comment by kazumihirose** [comment] 2020-05-30 21:49
I tried the same settings on android 10 in live mode.
But the same problem comes up.
```
Java.Lang.IllegalStateException: 'Nonexistent connection status for service config: com.google.android.gms.nearby.exposurenotification.START'
``

**Comment by kazumihirose** [comment] 2020-05-30 22:37
Checked in our project and our project uses nuget.
and fixed the manifest.
But In this case I get an error.

**Comment by Redth** [comment] 2020-05-31 11:03
So if you reference the source code directly it is working, but not the nuget?

**Comment by Redth** [comment] 2020-05-31 11:58
Ok it seems like this was all caused by missing a `Exported = true` in the attribute that we used to generate the AndroidManifest.xml's broadcast receiver declaration.  Comparing to Google's sample, this was missing, and is also generally required to make a broadcast receiver work with external applications/services on a device.

**Closed** 2020-05-31 12:19 UTC
